name: proto_schemas
description: "Dart client code gegenereerd uit proto definitions."
version: 2.1.3

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  protobuf: ^4.1.1
  grpc: ^4.1.0
  fixnum: ^1.1.1