name: Generate Proto Files
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  delete:
permissions:
  contents: write
  pull-requests: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Buf
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
      - run: buf dep update
      - run: buf generate
      - run: buf lint
      - run: buf push
        if: github.ref == 'refs/heads/main'

      - name: Commit and push generated files
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gen/ lib/
          git diff --staged --quiet || git commit -m "chore: auto-generate proto files [skip ci]"
          git push
